-- Buscador de productos con filtros (fase 1).
-- Ver docs/superpowers/specs/2026-08-14-buscador-productos-filtros-design.md

CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pg_trgm  WITH SCHEMA extensions;

-- Normalización única para TODA búsqueda de texto del sistema: minúsculas,
-- sin acentos, sin espacios de más.
--
-- Tiene que ser IMMUTABLE para poder indexarla, y unaccent() por sí sola NO
-- lo es (depende del diccionario activo, que se puede cambiar en caliente).
-- Pasarle el diccionario explícito como primer argumento la vuelve
-- determinística, y por eso este wrapper se puede marcar IMMUTABLE sin
-- mentir. Sin esto, el índice del final falla al crearse.
CREATE OR REPLACE FUNCTION texto_busqueda(t TEXT) RETURNS TEXT
LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$
    SELECT btrim(regexp_replace(
        lower(extensions.unaccent('extensions.unaccent'::regdictionary, coalesce(t, ''))),
        '\s+', ' ', 'g'))
$$;

CREATE TABLE marcas (
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE
);

-- Sin columna `activo` a propósito: las marcas no tienen pantalla de
-- administración, se mantienen solas desde la ficha del producto.
CREATE UNIQUE INDEX marcas_nombre_normalizado ON marcas (texto_busqueda(nombre));

CREATE TABLE vehiculos (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marca_auto TEXT NOT NULL,
    modelo     TEXT NOT NULL,
    -- Obligatorio. Para el repuesto que sirve para cualquier motor de ese
    -- auto existe el valor explícito 'Todos los motores': dejarlo vacío
    -- obligaría a decidir en cada consulta si vacío es "no sé" o "cualquiera".
    motor      TEXT NOT NULL,
    anio_desde INTEGER,
    anio_hasta INTEGER,
    activo     BOOLEAN NOT NULL DEFAULT true,
    UNIQUE (marca_auto, modelo, motor)
);

CREATE TABLE producto_vehiculos (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id INTEGER NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
    -- Sin CASCADE a propósito: borrar un vehículo que algún producto usa
    -- tiene que fallar, igual que hoy falla borrar un proveedor con
    -- productos. Se desactiva con `activo`, no se borra.
    vehiculo_id INTEGER NOT NULL REFERENCES vehiculos(id),
    UNIQUE (producto_id, vehiculo_id)
);

CREATE INDEX producto_vehiculos_vehiculo ON producto_vehiculos (vehiculo_id);

-- Índice para la búsqueda de texto. Sin esto, cada ILIKE '%algo%' recorre la
-- tabla entera: invisible con 29 productos de prueba, un problema real con
-- los ~6.000 del catálogo verdadero.
CREATE INDEX productos_texto_trgm ON productos USING gin (
    texto_busqueda(
        coalesce(nombre, '') || ' ' || coalesce(codigo, '') || ' ' ||
        coalesce(marca, '') || ' ' || coalesce(modelo_compatible, '')
    ) extensions.gin_trgm_ops
);

-- Agrega a `marcas` las que falten mirando productos.marca. Idempotente:
-- se puede volver a correr cuando se importe el catálogo real.
--
-- DISTINCT ON sobre el nombre normalizado es lo que hace que 'COBREQ',
-- 'Cobreq' y 'cobreq ' entren como UNA sola marca. Sin eso el desplegable
-- prolijo termina siendo tres veces la misma marca, peor que el texto libre
-- que vino a reemplazar.
CREATE OR REPLACE FUNCTION sembrar_marcas_desde_productos() RETURNS INTEGER
LANGUAGE plpgsql AS $$
DECLARE
    agregadas INTEGER;
BEGIN
    WITH candidatas AS (
        SELECT DISTINCT ON (texto_busqueda(marca)) btrim(marca) AS nombre
        FROM productos
        WHERE marca IS NOT NULL AND texto_busqueda(marca) <> ''
        ORDER BY texto_busqueda(marca), btrim(marca)
    ), insertadas AS (
        INSERT INTO marcas (nombre)
        SELECT c.nombre FROM candidatas c
        WHERE NOT EXISTS (
            SELECT 1 FROM marcas m WHERE texto_busqueda(m.nombre) = texto_busqueda(c.nombre)
        )
        RETURNING 1
    )
    SELECT count(*) INTO agregadas FROM insertadas;
    RETURN agregadas;
END;
$$;

SELECT sembrar_marcas_desde_productos();
