-- Esquema inicial, traducido desde la constante SCHEMA de core/database.py
-- (SQLite) más todas las columnas que hoy agrega _migrar() ahí mismo. Ese
-- mecanismo de migración incremental desaparece: de acá en más, cualquier
-- columna nueva se agrega con una migración de Supabase propia.
--
-- Reglas de traducción aplicadas (ver el spec de la Tarea 2):
--   * INTEGER PRIMARY KEY AUTOINCREMENT -> INTEGER GENERATED BY DEFAULT AS
--     IDENTITY PRIMARY KEY
--   * REAL en las 21 columnas de plata -> NUMERIC(12,2) (flotante acumula
--     error de redondeo; ARCA exige neto + IVA = total exacto)
--   * TEXT DEFAULT CURRENT_TIMESTAMP -> TIMESTAMPTZ NOT NULL DEFAULT now()
--     (gana sobre la regla de abajo)
--   * TEXT en fecha/fecha_alta/fecha_inicio/fecha_fin/fecha_pedido_pendiente
--     -> DATE
--   * TEXT en fecha_creacion/bloqueado_hasta -> TIMESTAMPTZ
--   * INTEGER usado como booleano (activo, debe_cambiar_password,
--     conciliado, pedido_pendiente) -> BOOLEAN
--   * usuarios.id -> UUID PRIMARY KEY DEFAULT gen_random_uuid() (se liga a
--     auth.users de Supabase Auth en el Plan 2)
--
-- Excepción a la regla de fechas: cuenta_corriente_movimientos.fecha y
-- movimientos_no_facturados.fecha tienen default CURRENT_TIMESTAMP en
-- SQLite (son marca de tiempo, no fecha simple) -> TIMESTAMPTZ.
--
-- Tablas creadas en orden de dependencia para que las FK resuelvan.

-- ---------------------------------------------------------------------
-- clientes
-- ---------------------------------------------------------------------
CREATE TABLE clientes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    telefono TEXT,
    email TEXT,
    direccion TEXT,
    cuit_dni TEXT,
    fecha_alta DATE NOT NULL,
    -- agregado por _migrar(): tipo_cliente TEXT NOT NULL DEFAULT 'particular'
    tipo_cliente TEXT NOT NULL DEFAULT 'particular',
    -- agregado por _migrar(): condicion_iva TEXT NOT NULL DEFAULT 'consumidor_final'
    -- (Factura A si es responsable_inscripto con CUIT, si no Factura B)
    condicion_iva TEXT NOT NULL DEFAULT 'consumidor_final'
);

-- ---------------------------------------------------------------------
-- proveedores
-- ---------------------------------------------------------------------
CREATE TABLE proveedores (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    telefono TEXT,
    email TEXT,
    direccion TEXT,
    cuit TEXT,
    activo BOOLEAN NOT NULL DEFAULT true
);

-- ---------------------------------------------------------------------
-- categorias
-- ---------------------------------------------------------------------
CREATE TABLE categorias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    activo BOOLEAN NOT NULL DEFAULT true
);

-- ---------------------------------------------------------------------
-- subcategorias (cuelga siempre de una única categoría, jerarquía estricta)
-- ---------------------------------------------------------------------
CREATE TABLE subcategorias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    categoria_id INTEGER NOT NULL REFERENCES categorias(id),
    activo BOOLEAN NOT NULL DEFAULT true,
    UNIQUE (categoria_id, nombre)
);

-- ---------------------------------------------------------------------
-- productos
-- ---------------------------------------------------------------------
CREATE TABLE productos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo TEXT UNIQUE,
    nombre TEXT NOT NULL,
    categoria TEXT NOT NULL DEFAULT 'Otros',
    -- agregado por _migrar(): subcategoria TEXT (texto libre, no FK, mismo
    -- criterio denormalizado que ya usaba categoria)
    subcategoria TEXT,
    marca TEXT,
    modelo_compatible TEXT,
    -- agregado por _migrar(): codigo_barras TEXT (columna ya presente en la
    -- constante SCHEMA actual, listada también en _migrar() por compatibilidad
    -- con bases viejas creadas antes de que SCHEMA la incluyera)
    codigo_barras TEXT,
    -- agregado por _migrar(): imagen TEXT (foto del producto)
    imagen TEXT,
    precio_costo NUMERIC(12,2) NOT NULL DEFAULT 0,
    precio_venta NUMERIC(12,2) NOT NULL DEFAULT 0,
    stock_actual INTEGER NOT NULL DEFAULT 0,
    stock_minimo INTEGER NOT NULL DEFAULT 2,
    proveedor_id INTEGER REFERENCES proveedores(id),
    -- agregado por _migrar(): pedido_pendiente INTEGER NOT NULL DEFAULT 0
    -- (columna ya presente en SCHEMA actual, mismo caso que codigo_barras)
    pedido_pendiente BOOLEAN NOT NULL DEFAULT false,
    -- agregado por _migrar(): fecha_pedido_pendiente TEXT (idem)
    fecha_pedido_pendiente DATE
);

-- ---------------------------------------------------------------------
-- ventas
-- ---------------------------------------------------------------------
CREATE TABLE ventas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    cliente_id INTEGER REFERENCES clientes(id),
    total NUMERIC(12,2) NOT NULL DEFAULT 0,
    metodo_pago TEXT DEFAULT 'Efectivo',
    tipo_comprobante TEXT DEFAULT 'Remito',
    numero_comprobante TEXT,
    -- agregado por _migrar(): columnas de facturación electrónica AFIP/ARCA
    cae TEXT,
    cae_vencimiento TEXT,
    punto_venta_arca INTEGER,
    numero_factura_arca INTEGER,
    facturacion_estado TEXT,
    facturacion_error TEXT,
    -- agregado por _migrar(): id_operacion TEXT (agrupa pagos mixtos, ver
    -- /ventas/dia)
    id_operacion TEXT,
    -- agregado por _migrar(): desglose neto/IVA de la Factura A/B emitida
    imp_neto NUMERIC(12,2),
    imp_iva NUMERIC(12,2)
);

-- ---------------------------------------------------------------------
-- venta_items
-- ---------------------------------------------------------------------
CREATE TABLE venta_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id INTEGER NOT NULL REFERENCES ventas(id),
    producto_id INTEGER NOT NULL REFERENCES productos(id),
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(12,2) NOT NULL,
    subtotal NUMERIC(12,2) NOT NULL
);

-- ---------------------------------------------------------------------
-- compras
-- ---------------------------------------------------------------------
CREATE TABLE compras (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    proveedor_id INTEGER REFERENCES proveedores(id),
    total NUMERIC(12,2) NOT NULL DEFAULT 0,
    numero_factura_proveedor TEXT
);

-- ---------------------------------------------------------------------
-- compra_items
-- ---------------------------------------------------------------------
CREATE TABLE compra_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id INTEGER NOT NULL REFERENCES compras(id),
    producto_id INTEGER NOT NULL REFERENCES productos(id),
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(12,2) NOT NULL,
    subtotal NUMERIC(12,2) NOT NULL
);

-- ---------------------------------------------------------------------
-- producto_proveedor (comparador de precios por proveedor)
-- ---------------------------------------------------------------------
CREATE TABLE producto_proveedor (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id INTEGER NOT NULL REFERENCES productos(id),
    proveedor_id INTEGER NOT NULL REFERENCES proveedores(id),
    precio_costo NUMERIC(12,2) NOT NULL DEFAULT 0,
    codigo_proveedor TEXT,
    UNIQUE (producto_id, proveedor_id)
);

-- ---------------------------------------------------------------------
-- pedidos_web (carrito en tránsito de la tienda online, no un segundo
-- inventario de pedidos: al confirmarse el pago pasa a ventas/venta_items)
-- ---------------------------------------------------------------------
CREATE TABLE pedidos_web (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    nombre_cliente TEXT NOT NULL,
    telefono TEXT,
    email TEXT,
    direccion TEXT,
    cuit_dni TEXT,
    total NUMERIC(12,2) NOT NULL DEFAULT 0,
    estado TEXT NOT NULL DEFAULT 'pendiente_pago',
    mp_preference_id TEXT,
    mp_payment_id TEXT,
    venta_id INTEGER REFERENCES ventas(id)
);

-- ---------------------------------------------------------------------
-- pedido_web_items
-- ---------------------------------------------------------------------
CREATE TABLE pedido_web_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id INTEGER NOT NULL REFERENCES pedidos_web(id),
    producto_id INTEGER NOT NULL REFERENCES productos(id),
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(12,2) NOT NULL,
    subtotal NUMERIC(12,2) NOT NULL
);

-- ---------------------------------------------------------------------
-- usuarios (id como uuid desde ahora: en el Plan 2 se liga a auth.users de
-- Supabase Auth, así no hace falta cambiar el tipo dos veces)
-- ---------------------------------------------------------------------
CREATE TABLE usuarios (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    nombre TEXT NOT NULL,
    rol TEXT NOT NULL DEFAULT 'empleado',
    activo BOOLEAN NOT NULL DEFAULT true,
    debe_cambiar_password BOOLEAN NOT NULL DEFAULT false,
    intentos_fallidos INTEGER NOT NULL DEFAULT 0,
    bloqueado_hasta TIMESTAMPTZ,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- cuenta_corriente_movimientos (cargos/pagos de clientes con cuenta
-- corriente; producto_id quedó de una versión anterior de un solo producto
-- por cargo, ya no se usa para cargos nuevos -- ver
-- cuenta_corriente_movimiento_items)
-- ---------------------------------------------------------------------
CREATE TABLE cuenta_corriente_movimientos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id INTEGER NOT NULL REFERENCES clientes(id),
    cliente_tercero_nombre TEXT,
    -- CUIT/DNI del tercero real a nombre de quien se factura el cargo (si
    -- no se carga, se factura al cliente/mecánico dueño de la cuenta)
    tercero_cuit_dni TEXT,
    -- agregado por _migrar(): condición IVA del tercero (solo relevante si
    -- se cargó tercero_cuit_dni; mismos valores que clientes.condicion_iva)
    tercero_condicion_iva TEXT,
    producto_id INTEGER REFERENCES productos(id),
    monto NUMERIC(12,2) NOT NULL,
    tipo TEXT NOT NULL,
    -- fecha con default CURRENT_TIMESTAMP en SQLite: es una marca de tiempo,
    -- no una fecha simple -> timestamptz (ver nota al principio del archivo)
    fecha TIMESTAMPTZ NOT NULL DEFAULT now(),
    venta_id INTEGER REFERENCES ventas(id),
    observaciones TEXT,
    cae TEXT,
    cae_vencimiento TEXT,
    punto_venta_arca INTEGER,
    numero_factura_arca INTEGER,
    facturacion_estado TEXT,
    facturacion_error TEXT,
    -- agregado por _migrar(): desglose neto/IVA de la factura del movimiento
    imp_neto NUMERIC(12,2),
    imp_iva NUMERIC(12,2),
    -- agregado por _migrar(): tipo_comprobante TEXT ("Factura A"/"Factura B")
    tipo_comprobante TEXT
);

-- ---------------------------------------------------------------------
-- cuenta_corriente_movimiento_items (productos de un cargo, mismo patrón
-- que venta_items; el stock se descuenta al confirmarse el cargo)
-- ---------------------------------------------------------------------
CREATE TABLE cuenta_corriente_movimiento_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movimiento_id INTEGER NOT NULL REFERENCES cuenta_corriente_movimientos(id),
    producto_id INTEGER NOT NULL REFERENCES productos(id),
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(12,2) NOT NULL,
    subtotal NUMERIC(12,2) NOT NULL
);

-- ---------------------------------------------------------------------
-- movimientos_no_facturados (compras/ventas de stock que no pasan por
-- compras/ventas ni por AFIP, pero sí impactan productos.stock_actual)
-- ---------------------------------------------------------------------
CREATE TABLE movimientos_no_facturados (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- fecha con default CURRENT_TIMESTAMP en SQLite: es una marca de tiempo,
    -- no una fecha simple -> timestamptz (ver nota al principio del archivo)
    fecha TIMESTAMPTZ NOT NULL DEFAULT now(),
    tipo TEXT NOT NULL,
    producto_id INTEGER NOT NULL REFERENCES productos(id),
    cantidad INTEGER NOT NULL,
    precio NUMERIC(12,2) NOT NULL DEFAULT 0,
    contraparte TEXT,
    observaciones TEXT,
    conciliado BOOLEAN NOT NULL DEFAULT false
);

-- ---------------------------------------------------------------------
-- promociones_aplicadas (descuentos aprobados manualmente para un cliente
-- puntual, ver /clientes/top)
-- ---------------------------------------------------------------------
CREATE TABLE promociones_aplicadas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id INTEGER NOT NULL REFERENCES clientes(id),
    porcentaje_o_monto NUMERIC(12,2) NOT NULL,
    tipo TEXT NOT NULL,
    alcance TEXT NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE,
    aprobado_por TEXT,
    -- fecha_aprobacion tiene default CURRENT_TIMESTAMP en SQLite: la regla
    -- de CURRENT_TIMESTAMP gana sobre la regla general de columnas "fecha*"
    -- -> timestamptz, no date
    fecha_aprobacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- promocion_productos (alcance puntual de una promoción a productos
-- específicos, tabla intermedia)
-- ---------------------------------------------------------------------
CREATE TABLE promocion_productos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promocion_id INTEGER NOT NULL REFERENCES promociones_aplicadas(id),
    producto_id INTEGER NOT NULL REFERENCES productos(id)
);
